### ISSUE TITLE
qt_defaultDpi() issue

### ISSUE THREAD

**Issue by unrealsolver** [wkhtmltopdf/qt#13]
Could someone explain, what it was? `git push --force`?
![qt_defaultdpi](https://cloud.githubusercontent.com/assets/1101771/5355525/1864a492-7fa5-11e4-8c37-ed32f9b6b930.PNG)
I've removed repo and cloned again. Looks fine now.

**Comment by ashkulz** [comment]
Yeah, I did a `git push -f`, sorry about that -- hardly anyone clones this repository and the fix happened within a short period (10 hours or so).
