### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by nlouahedj** [wkhtmltopdf/qt#17]
I was trying to compile qt on archlinux but the compilation failed.
using this config : ./configure -static -prefix /opt/qt/
then: make
here is the output [qt error.txt](https://github.com/wkhtmltopdf/qt/files/76034/qt.error.txt)

**Comment by ashkulz** [comment]
Using it outside of `build.py` is not supported, you're on your own.

**Comment by nlouahedj** [comment]
Thank you for your help.
