### ISSUE TITLE
Need to partially convert HTML to PDF document

### ISSUE THREAD

**Issue by premkumar-sundaramoorthy** [wkhtmltopdf/qt#30]
Hi All,

i am using qtwebkit 5.5 for convert HTML to PDF in that i want to partially convert HTML page to PDF by specifying HTML elements (div,Table,chart,image etc) instead of convert hole page for example i am having HTML page with more then one <div> content from that i want to convert any one of the div content as PDF by specifying its ID . please share your views .

Thanks in advance.

**Comment by ashkulz** [comment]
Use CSS via `--user-style-sheet` to hide the other elements using `display: none`.
