### ISSUE TITLE
make[1]: *** [Makefile:2578: .obj/debug-shared/qvariableloader.o] Error 1

### ISSUE THREAD

**Issue by saigkill** [wkhtmltopdf/qt#32]
Actually i try to build wkhtmltopdf-qt for openSUSE. The build breaks there:

[  346s] g++ -c -m64 -pipe -g -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DQT_SHARED -DQT_BUILD_XMLPATTERNS_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_NETWORK_LIB -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/linux-g++-64 -I. -I../../include/QtCore -I../../include/QtNetwork -I../../include -I../../include/QtXmlPatterns -I.rcc/debug-shared -Iacceltree -Idata -Iapi -Ienvironment -Iexpr -Ifunctions -Iiterators -Ijanitors -Iparser -Ischema -Itype -Iutils -I.moc/debug-shared -o .obj/debug-shared/qabstracturiresolver.o api/qabstracturiresolver.cpp
[  346s] In file included from api/qcoloringmessagehandler_p.h:57:0,
[  346s]                  from api/qxmlquery_p.h:67,
[  346s]                  from api/qvariableloader.cpp:54:
[  346s] api/qcoloroutput_p.h:74:60: warning: result of '(1048575 << 20)' requires 41 bits to represent, but 'int' only has 32 bits [-Wshift-overflow=]
[  346s]              BackgroundMask  = ((1 << BackgroundShift) - 1) << BackgroundShift
[  346s]                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
[  346s] api/qcoloroutput_p.h:74:60: error: shift expression '(1048575 << 20)' overflows [-fpermissive]
[  346s] api/qcoloroutput_p.h:74:63: error: enumerator value for 'BackgroundMask' is not an integer constant
[  346s]              BackgroundMask  = ((1 << BackgroundShift) - 1) << BackgroundShift
[  346s]                                                                ^~~~~~~~~~~~~~~
[  346s] g++ -c -m64 -pipe -g -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DQT_SHARED -DQT_BUILD_XMLPATTERNS_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_NETWORK_LIB -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/linux-g++-64 -I. -I../../include/QtCore -I../../include/QtNetwork -I../../include -I../../include/QtXmlPatterns -I.rcc/debug-shared -Iacceltree -Idata -Iapi -Ienvironment -Iexpr -Ifunctions -Iiterators -Ijanitors -Iparser -Ischema -Itype -Iutils -I.moc/debug-shared -o .obj/debug-shared/qabstractxmlnodemodel.o api/qabstractxmlnodemodel.cpp
[  347s] g++ -c -m64 -pipe -g -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -fPIC -DQT_SHARED -DQT_BUILD_XMLPATTERNS_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_NETWORK_LIB -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/linux-g++-64 -I. -I../../include/QtCore -I../../include/QtNetwork -I../../include -I../../include/QtXmlPatterns -I.rcc/debug-shared -Iacceltree -Idata -Iapi -Ienvironment -Iexpr -Ifunctions -Iiterators -Ijanitors -Iparser -Ischema -Itype -Iutils -I.moc/debug-shared -o .obj/debug-shared/qabstractxmlpullprovider.o api/qabstractxmlpullprovider.cpp
[  347s] make[1]: *** [Makefile:2578: .obj/debug-shared/qvariableloader.o] Error 1

The full buildlog can be viewed there: https://build.opensuse.org/build/Documentation:Publican/openSUSE_Tumbleweed/x86_64/wkhtmltopdf-qt/_log
The current patches and rpm-specfile can be viewed there: https://build.opensuse.org/package/show/Documentation:Publican/wkhtmltopdf-qt

**Comment by ashkulz** [comment]
Looks like an [upstream bug with gcc6](https://bugzilla.redhat.com/show_bug.cgi?id=1305218) but Qt 4.8.7 is now frozen and hence needs to be patched directly -- I think the [patch in Fedora](https://src.fedoraproject.org/cgit/rpms/qt.git/tree/qt-everywhere-opensource-src-4.8.7-gcc6.patch) should work.

**Comment by ashkulz** [comment]
@saigkill: looks like you are familiar with OBS, would you be interested in helping to set up a cross-distro build using it?

**Comment by saigkill** [comment]
@ashkulz Actually i haven't a significant experience with cross-distro on OBS. So i just have build packages for openSUSE and some for the Fedora Target. So i think i would'nt be a real help.

**Comment by mckaygerhard** [comment]
why still patchin qt, why the project not use the sources as must do!?
