### ISSUE TITLE
build breaks while problem with typename

### ISSUE THREAD

**Issue by saigkill** [wkhtmltopdf/qt#33]
Actual i have a build break:

[  679s] ../3rdparty/javascriptcore/JavaScriptCore/wtf/HashTable.h:272:89: error: call of overloaded 'swap(std::pair<QTWTF::RefPtr<QTJSC::UStringImpl>, QTJSC::OffsetLocation>&, std::pair<QTWTF::RefPtr<QTJSC::UStringImpl>, QTJSC::OffsetLocation>&)' is ambiguous
[  679s]      template<typename T> struct Mover<T, true> { static void move(T& from, T& to) { swap(from, to); } };
[  679s]                                                                                      ~~~~^~~~~~~~~~
[  679s] In file included from /usr/include/c++/6/utility:70:0,
[  679s]                  from /usr/include/c++/6/algorithm:60,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/wtf/RefPtr.h:24,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/wtf/HashFunctions.h:24,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/wtf/HashTraits.h:24,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/JSValue.h:33,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/interpreter/Register.h:32,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/ArgList.h:25,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/JSObject.h:26,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/InternalFunction.h:27,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.h:29,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.cpp:28:
[  679s] /usr/include/c++/6/bits/stl_pair.h:471:5: note: candidate: void std::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&) [with _T1 = QTWTF::RefPtr<QTJSC::UStringImpl>; _T2 = QTJSC::OffsetLocation]
[  679s]      swap(pair<_T1, _T2>& __x, pair<_T1, _T2>& __y)
[  679s]      ^~~~
[  679s] In file included from /usr/include/c++/6/bits/nested_exception.h:40:0,
[  679s]                  from /usr/include/c++/6/exception:171,
[  679s]                  from /usr/include/c++/6/new:40,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/wtf/FastMalloc.h:27,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/config.h:68,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.cpp:26:
[  679s] /usr/include/c++/6/bits/move.h:179:5: note: candidate: typename std::enable_if<std::__and_<std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&) [with _Tp = std::pair<QTWTF::RefPtr<QTJSC::UStringImpl>, QTJSC::OffsetLocation>; typename std::enable_if<std::__and_<std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type = void]
[  679s]      swap(_Tp& __a, _Tp& __b)
[  679s]      ^~~~
[  679s] In file include[  657.785875] serial8250: too much work for irq4
[  679s] d from ../3rdparty/javascriptcore/JavaScriptCore/wtf/HashSet.h:25:0,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/ArgList.h:26,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/JSObject.h:26,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/runtime/InternalFunction.h:27,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.h:29,
[  679s]                  from ../3rdparty/javascriptcore/JavaScriptCore/API/JSCallbackFunction.cpp:28:
[  679s] ../3rdparty/javascriptcore/JavaScriptCore/wtf/HashTable.h:264:50: note: candidate: void QTWTF::swap(std::pair<_T1, _T2>&, std::pair<_T1, _T2>&) [with T = QTWTF::RefPtr<QTJSC::UStringImpl>; U = QTJSC::OffsetLocation]
[  679s]      template<typename T, typename U> inline void swap(pair<T, U>& a, pair<T, U>& b)
[  679s]                                                   ^~~~
[  679s] make[1]: *** [Makefile:2647: obj/debug/JSCallbackFunction.o] Error 1

Full build log: https://build.opensuse.org/build/Documentation:Publican/openSUSE_Tumbleweed/x86_64/wkhtmltopdf-qt/_log

**Comment by saigkill** [comment]
Build Break happens also with the current 4.8.7 branch

**Comment by ashkulz** [comment]
These are problems of old Qt with newer compilers, should be patched elsewhere.

**Comment by saigkill** [comment]
What would be a good way to patch this?

**Comment by ashkulz** [comment]
Search for similar error, distro using updated compiler would have a patch.

**Comment by hakimio** [comment]
Following fix might do the trick:
https://github.com/ElfoLiNk/qt/commit/644969400d93e53b7b0793bd39f301102e6eb59c

**Comment by ashkulz** [comment]
This should be fixed with ce61dc78a0a68428848bfc6531b9ef18019d9134 and 59dd6c8c2fbc1995f890d84d4bc08e02ea4c0eb6 -- compilation should work with most distros now.
