### ISSUE TITLE
HTML input fields not fillible

### ISSUE THREAD

**Issue by LambdaSoftworks** [wkhtmltopdf/qt#34]
I just updated from 12.3 to 12.4 to fix an issue where fallible fields do not show text when printed. After the update those input fields are no longer fillable, and I have --enable-forms in the CLI. This is a PHP script I am working with. For now I have reverted to the old version so my users are not impacted, but any advice on this would be very appreciated.

**Comment by ashkulz** [comment]
Can you open a issue in the main repository for this? Also does reverting the fixes for wkhtmltopdf/wkhtmltopdf#2004 i.e. [these changes](https://github.com/wkhtmltopdf/qt/compare/6f025714379c0c004395fcde47396780b84716e3...c6e2d6b4a84bfb28a9aa2d45f7d1de4e92281e95) work?
