### ISSUE TITLE
Homebrew fatal error: branch wk_4.8.6 not found...

### ISSUE THREAD

**Issue by stevecj** [wkhtmltopdf/qt#5]
I was trying to follow the first instruction on http://natepinchot.com/2014/01/31/building-static-wkhtmltopdf/ for OS X and Homebrew, which is...

```
brew install https://raw.github.com/npinchot/homebrew/wkhtmltopdf_static_qt/Library/Formula/qt-wkhtmltopdf.rb
```

I got the following output...

```
==> Cloning https://github.com/wkhtmltopdf/qt.git
Cloning into '/Library/Caches/Homebrew/qt-wkhtmltopdf--git'...
warning: Could not find remote branch wk_4.8.6 to clone.
fatal: Remote branch wk_4.8.6 not found in upstream origin
Unexpected end of command stream
Error: Failed to download resource "qt-wkhtmltopdf"
Failure while executing: git clone --depth 1 --branch wk_4.8.6 https://github.com/wkhtmltopdf/qt.git /Library/Caches/Homebrew/qt-wkhtmltopdf--git
```

Looking here, I see that there is a 4.8.5 branch, but not 4.8.6. Is there a problem that needs to be fixed for this to work? Alternatively, is there a different set of instructions that I should be following to install wkhtmltopdf with static QT via Homebrew?

**Comment by ashkulz** [comment]
use the `wk_4.8` branch.

**Comment by ashkulz** [comment]
Also, you might want to use the `build_osx.sh` script in the wkhtmltopdf source.

**Comment by stevecj** [comment]
How would I use the wk_4.8 branch using homebrew? Homebrew tried to check out wk_4.8.6 when I tried to install using https://raw.github.com/npinchot/homebrew/wkhtmltopdf_static_qt/Library/Formula/qt-wkhtmltopdf.rb. I did not specify the version in any way.

**Comment by ashkulz** [comment]
the build script mentioned was authored by @npinchot so you might want to use it -- the blog post is from before it was included in wkhtmltopdf.

**Comment by stevecj** [comment]
I was trying to use that one because `brew install wkhtmltopdf` currently says "No available formula for wkhtmltopdf", so I was Googling for any other instructions. I did run `brew update` first, by the way, and `brew doctor` reports no problems.

**Comment by bonbonlanges** [comment]
hey guys. has there any been recent development with this thread? i am having the same issue as well.

**Comment by ashkulz** [comment]
Sorry, wkhtmltopdf is not supported on Mac OS X. I don't have a Mac and @npinchot doesn't have time to support Mac OS X in the build script and make builds -- so that will remain as the status for the 0.12.1 release.
